/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef GAIDWRAPPER_AUTODEFS_H
#define GAIDWRAPPER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GAIDWRAPPER_NAME "GAIDWrapper"
#define S3E_EXT_GAIDWRAPPER_HASH 0x5d2267b

#endif /* !GAIDWRAPPER_AUTODEFS_H */
