/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_GAIDWRAPPER_H
#define S3E_EXT_GAIDWRAPPER_H

#include <s3eTypes.h>

typedef enum s3eGAIDCallback
{
    S3E_GAID_RECEIVED,
    S3E_GAID_CALLBACK_MAX
} s3eGAIDCallback;

/**
 * This struct stores Google Advertising Id information.
 */
typedef struct s3eGoogleAdvertisingIdInformation
{
    /**
     * The device Google Advertising Id.
     */
    const char* m_Gaid;

    /**
     * Whether Limit Ad Tracking is enabled.
     */
    bool m_isLAT;

} s3eGoogleAdvertisingIdInformation;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the GAIDWrapper extension is available.
 */
s3eBool GAIDWrapperAvailable();

void GAIDGetGoogleAdvertisingId(s3eCallback cb);

S3E_END_C_DECL

#endif /* !S3E_EXT_GAIDWRAPPER_H */
