/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "GAIDWrapper_autodefs.h"
#include "s3eEdk.h"
#include "GAIDWrapper.h"
//Declarations of Init and Term functions
extern s3eResult GAIDWrapperInit();
extern void GAIDWrapperTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void GAIDGetGoogleAdvertisingId_wrap(s3eCallback cb)
{
    IwTrace(GAIDWRAPPER_VERBOSE, ("calling GAIDWrapper func on main thread: GAIDGetGoogleAdvertisingId"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)GAIDGetGoogleAdvertisingId, 1, cb);
}

#define GAIDGetGoogleAdvertisingId GAIDGetGoogleAdvertisingId_wrap

#endif

void GAIDWrapperRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)GAIDGetGoogleAdvertisingId;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("GAIDWrapper", funcPtrs, sizeof(funcPtrs), flags, GAIDWrapperInit, GAIDWrapperTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int GAIDWrapperStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&GAIDWrapperRegisterExt;
    return 0;
}

int g_GAIDWrapperVal = GAIDWrapperStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    GAIDWrapperRegisterExt();
}
#endif

#endif
