/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef IFAWRAPPER_AUTODEFS_H
#define IFAWRAPPER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IFAWRAPPER_NAME "IFAWrapper"
#define S3E_EXT_IFAWRAPPER_HASH 0xa5e30816

#endif /* !IFAWRAPPER_AUTODEFS_H */
